// The reactive mirror of the backend's AppState. Slices match faf-domain.
// Tabs read with `useAppStore(s => s.state.<slice>)` and never mutate directly,
// the only writes are `apply` (from events) and `hydrate` (initial snapshot).

import { create } from "zustand";
import type { AppEvent, AppState } from "../ipc/bindings";
import { EMPTY_REPLAY_QUERY } from "../shared/replayQuery";
import { EMPTY_MAP_QUERY, EMPTY_MOD_QUERY } from "../shared/vaultQuery";
import { applyEvent } from "./reducer";

const INITIAL: AppState = {
  session: { backendVersion: "", status: "disconnected", offlineAuth: false },
  auth: { status: "loggedOut", player: null, error: null, mode: "account" },
  nav: { activeTab: "news" },
  notifications: { items: [] },
  chat: {
    status: "disconnected",
    username: "",
    channels: [],
    retainedHistories: [],
    activeChannel: "",
    showJoinsParts: false,
    serverAutoJoin: [],
  },
  lobby: {
    status: "disconnected",
    games: [],
    liveGames: [],
    join: { type: "idle" },
    matchmakerQueues: [],
    matchmaking: { type: "idle" },
    party: { ownerId: null, members: [] },
    vetoes: [],
    playMode: "custom",
    availableAvatars: [],
    avatarListStatus: "idle",
    avatarListError: "",
    avatarSelectionStatus: "idle",
    avatarSelectionError: "",
    hostPrefill: null,
  },
  replays: {
    status: { type: "idle" },
    lastWarning: null,
    liveTracking: null,
    vault: [],
    vaultStatus: { type: "idle" },
    vaultQuery: EMPTY_REPLAY_QUERY,
    vaultHasMore: false,
    vaultTotalPages: null,
    vaultTotalRecords: null,
    downloadStatus: { type: "idle" },
    featuredMods: [],
    local: [],
    localStatus: { type: "idle" },
  },
  maps: {
    vault: [],
    vaultStatus: { type: "idle" },
    browse: [],
    browseStatus: { type: "idle" },
    browseQuery: EMPTY_MAP_QUERY,
    browseTotalPages: null,
    browseTotalRecords: null,
    installed: [],
    installedStatus: { type: "idle" },
    installStatus: { type: "idle" },
    matchmakerPools: {},
    matchmakerPoolsStatus: { type: "idle" },
  },
  mapGenerator: {
    status: { type: "idle" },
    latestVersion: "",
    availableVersions: [],
    selectedVersion: null,
    optionLists: {
      symmetries: [],
      styles: [],
      terrainStyles: [],
      textureStyles: [],
      resourceStyles: [],
      propStyles: [],
    },
    // Mirrors `impl Default for GeneratorOptions` in faf-domain.
    options: {
      version: null,
      spawnCount: 6,
      numTeams: 2,
      mapSize: 512,
      seed: "",
      generationType: "casual",
      symmetry: "",
      symmetries: [],
      style: "",
      styles: [],
      terrainStyle: "",
      terrainStyles: [],
      textureStyle: "",
      textureStyles: [],
      resourceStyle: "",
      resourceStyles: [],
      propStyle: "",
      propStyles: [],
      reclaimDensity: null,
      reclaimDensityMin: null,
      reclaimDensityMax: null,
      resourceDensity: null,
      resourceDensityMin: null,
      resourceDensityMax: null,
      numToGenerate: null,
      debug: false,
      visualize: false,
      previewPath: "",
      outputPath: "",
      commandLineArgs: "",
    },
    previews: {},
    validation: [],
    predictedName: "",
    decoded: {},
    helpText: "",
    presets: [],
  },
  mods: {
    vault: [],
    vaultStatus: { type: "idle" },
    browse: [],
    browseStatus: { type: "idle" },
    browseQuery: EMPTY_MOD_QUERY,
    browseTotalPages: null,
    browseTotalRecords: null,
    installed: [],
    installedStatus: { type: "idle" },
    installStatus: { type: "idle" },
    toggleStatus: { type: "idle" },
  },
  leaderboard: {
    mode: "ratings",
    ratingLeaderboards: [],
    leagues: [],
    catalogStatus: { type: "idle" },
    ratingQuery: {
      leaderboard: "global",
      page: 1,
      pageSize: 100,
      activeOnly: true,
      updatedAfter: null,
      updatedBefore: null,
      player: "",
    },
    ratingPage: {
      entries: [],
      page: 1,
      pageSize: 100,
      totalPages: 1,
      totalResults: null,
    },
    ratingsStatus: { type: "idle" },
    selectedLeagueId: null,
    seasons: [],
    seasonsStatus: { type: "idle" },
    selectedSeasonId: null,
    seasonEntries: [],
    tiers: [],
    seasonStatus: { type: "idle" },
  },
  playerCard: {
    open: false,
    requestedLogin: "",
    profile: null,
    profileStatus: "idle",
    profileError: "",
    historyQuery: null,
    history: [],
    historyMaximum: null,
    historyPage: 0,
    historyTotalPages: 1,
    historyStatus: "idle",
    historyError: "",
    matchmakerProfile: null,
    matchmakerProfileStatus: "idle",
    matchmakerProfileError: "",
  },
  reporting: {
    open: false,
    playerId: null,
    login: "",
    status: { type: "idle" },
    history: [],
    historyStatus: { type: "idle" },
  },
  reviews: {
    target: null,
    reviews: [],
    summary: { total: 0, averageTenths: 0, counts: [0, 0, 0, 0, 0] },
    status: { type: "idle" },
    submit: { type: "idle" },
  },
  install: { gameReady: false, replayReady: false, checked: false },
  social: { friends: [], foes: [], players: [] },
  coop: {
    scenarios: [],
    missions: [],
    catalogStatus: { type: "idle" },
    selectedMissionId: null,
    playerCount: 0,
    leaderboard: [],
    leaderboardStatus: { type: "idle" },
  },
  tourney: {
    events: [],
    status: { type: "idle" },
    selectedId: null,
    detail: null,
    detailStatus: { type: "idle" },
    pending: null,
    actionError: null,
    entrantProfiles: [],
    chatRooms: [],
    openRoomId: null,
    chatPosts: [],
    chatStatus: { type: "idle" },
    articles: [],
    hosting: { loggedIn: false, allowed: false, pending: false },
    accountSearch: { query: "", matches: [], status: { type: "idle" } },
    series: [],
    seriesStatus: { type: "idle" },
    openSeries: null,
  },
  tutorials: {
    categories: [],
    tutorials: [],
    status: { type: "idle" },
    selectedId: null,
    launch: { type: "idle" },
  },
  uploads: { request: null, status: { type: "idle" } },
  galacticWar: {
    status: { type: "idle" },
    installedVersion: null,
    versions: null,
    belowMinimum: false,
    statistics: null,
    statisticsStatus: { type: "idle" },
  },
  clientUpdate: {
    status: { type: "idle" },
    currentVersion: "",
    release: null,
    dismissedVersion: "",
  },
  settings: {
    // Mirrors `impl Default for GeneratorOptions`, like the working copy above.
    mapGenerator: {
      version: null,
      spawnCount: 6,
      numTeams: 2,
      mapSize: 512,
      seed: "",
      generationType: "casual",
      symmetry: "",
      symmetries: [],
      style: "",
      styles: [],
      terrainStyle: "",
      terrainStyles: [],
      textureStyle: "",
      textureStyles: [],
      resourceStyle: "",
      resourceStyles: [],
      propStyle: "",
      propStyles: [],
      reclaimDensity: null,
      reclaimDensityMin: null,
      reclaimDensityMax: null,
      resourceDensity: null,
      resourceDensityMin: null,
      resourceDensityMax: null,
      numToGenerate: null,
      debug: false,
      visualize: false,
      previewPath: "",
      outputPath: "",
      commandLineArgs: "",
    },
    theme: "forgeDark",
    gamePath: "",
    replayGamePath: "",
    general: { startPage: "news" },
    appearance: { density: "comfortable", reduceMotion: false, uiScale: 100 },
    social: { playerNotes: [] },
    notifications: {
      enabled: true,
      desktop: true,
      sound: true,
      notifyWhenFocused: false,
      matchFound: true,
      privateMessages: true,
      mentions: true,
      friendOnline: true,
      friendOffline: true,
      friendPlaying: true,
      newCustomGames: false,
      newCustomGamesFriendsOnly: true,
      gameFull: true,
      gameLaunched: true,
      reviewReminder: true,
      partyInvites: true,
      volume: 70,
    },
    chat: {
      showJoinsParts: false,
      showTimestamps: true,
      use24HourTime: true,
      coloredNames: false,
      rosterWidth: 280,
      nameColors: {
        selfColor: "#ffdd00",
        friends: "#87cefa",
        foes: "#dc143c",
        moderators: "#32cd32",
        admins: "#ba55d3",
        players: {},
      },
      hideFoeMessages: true,
      visibleMessageLimit: 500,
      autoJoinChannels: [],
      autoJoinLanguageChannel: true,
      mutedPlayers: [],
      hiddenRosterCategories: [],
      readMarkers: {},
    },
    game: { additionalArguments: [], autoGenerateMaps: true },
    discord: { enabled: true, disallowJoins: false },
    connectivity: { adapter: "java", selectionVersion: 1 },
    updates: { automatic: true, preRelease: false },
    browsing: {
      customGamesView: "tiles",
      replaysView: "tiles",
      customGamesBrowser: {
        sort: "players",
        hidePrivate: false,
        hideModded: false,
        applyFilters: false,
        rules: [],
      },
      matchmakerUnselectedQueues: [],
      matchmakerFactions: ["UEF", "Aeon", "Cybran", "Seraphim"],
      liveReplayFilters: {
        search: "",
        gameType: "",
        featuredMod: "",
        activePlayers: "",
        maxPlayers: "",
        hideModded: false,
        hideSinglePlayer: false,
        friendsOnly: false,
      },
      hostGame: {
        title: "",
        featuredMod: "faf",
        visibility: "public",
        map: "",
        passwordEnabled: false,
        password: "",
        enforceRatingRange: false,
        ratingMin: 800,
        ratingMax: 1500,
      },
      favoriteMaps: [],
      mapVaultPreset: "recommended",
      modVaultPreset: "recommended",
      leaderboardRatingColumns: ["rating", "games", "wins", "winRate", "updated"],
      legacyStorageMigrated: false,
    },
  },
};

interface AppStore {
  state: AppState;
  /** True only after the authoritative Rust snapshot has replaced defaults. */
  hydrated: boolean;
  /** Apply a backend event (the only state-changing path, mirrors the backend). */
  apply: (event: AppEvent) => void;
  /** Replace state with a backend snapshot (initial hydration). */
  hydrate: (state: AppState) => void;
}

export const useAppStore = create<AppStore>((set) => ({
  state: INITIAL,
  hydrated: false,
  apply: (event) => set((s) => ({ state: applyEvent(s.state, event) })),
  hydrate: (state) => set({ state, hydrated: true }),
}));
