// AUTO-GENERATED by `cargo run -p faf-ipc --bin export-bindings`.
// Source of truth: crates/faf-domain. DO NOT EDIT BY HAND.

// This file has been generated by Specta. Do not edit this file manually.
export type AppCommand = { kind: "Session"; command: SessionCommand } | { kind: "Auth"; command: AuthCommand } | { kind: "Nav"; command: NavCommand } | { kind: "Lobby"; command: LobbyCommand } | { kind: "Settings"; command: SettingsCommand };

export type AppEvent = { kind: "Session"; event: SessionEvent } | { kind: "Auth"; event: AuthEvent } | { kind: "Nav"; event: NavEvent } | { kind: "Lobby"; event: LobbyEvent } | { kind: "Settings"; event: SettingsEvent };

/**  The complete client state. One field per domain slice. */
export type AppState = {
	session: SessionState,
	auth: AuthState,
	nav: NavState,
	lobby: LobbyState,
	settings: SettingsState,
};

/**  What the UI can ask the auth service to do. */
export type AuthCommand = { type: "login" } | { type: "logout" };

/**  The only way [`AuthState`] changes. */
export type AuthEvent = { type: "loginStarted" } | { type: "loggedIn"; payload: {
	player: Player,
} } | { type: "loginFailed"; payload: {
	message: string,
} } | { type: "loggedOut" };

export type AuthState = {
	status: AuthStatus,
	player: Player | null,
	error: string | null,
};

export type AuthStatus = "loggedOut" | "loggingIn" | "loggedIn" | "failed";

/**  Connection state of the backend session. */
export type ConnectionStatus = "disconnected" | "connecting" | "connected";

/**  An open game in the lobby. */
export type Game = {
	id: number,
	title: string,
	host: string,
	players: number,
	maxPlayers: number,
	map: string,
};

/**
 *  The server's `game_launch` order — everything the connectivity + launch chain
 *  (a later phase) needs to actually start the game. For now we only model and
 *  surface it; nothing acts on it yet. Mirrors the relevant fields of the Python
 *  client's `GameLaunchCommand` (`src/protocol/lobbyprotocol.py`).
 */
export type GameLaunch = {
	uid: number,
	/**  The featured mod (e.g. `faf`). Wire key is `mod`, a Rust keyword. */
	mod: string,
	name: string,
	mapname: string,
	gameType: string,
	ratingType: string,
	/**
	 *  Raw launch args from the server (the FA command line is built from these
	 *  plus client-side player info in the launch phase).
	 */
	args: string[],
};

/**
 *  Where a join attempt stands. Distinct from [`LobbyStatus`] (the connection):
 *  you can be `Connected` and `Idle`, or `Connected` and `Joining`.
 */
export type JoinState = { type: "idle" } | { type: "joining"; payload: {
	id: number,
} } | 
/**
 *  The server sent `game_launch`; the launch order is modeled. If real launch
 *  is enabled, the connectivity chain (ICE adapter + relay + game process)
 *  starts next, moving to [`Self::InGame`].
 */
{ type: "launched"; payload: {
	launch: GameLaunch,
} } | 
/**  The ICE adapter and game process were started; relay traffic is flowing. */
{ type: "inGame" } | 
/**  The server rejected the join (game not ready, host left, bad password). */
{ type: "failed"; payload: {
	id: number,
	reason: string,
} } | 
/**  The local launch chain failed (adapter/relay/game couldn't start). */
{ type: "launchFailed"; payload: {
	reason: string,
} };

export type LobbyCommand = { type: "connect" } | { type: "join"; payload: {
	id: number,
} } | { type: "disconnect" };

export type LobbyEvent = { type: "connecting" } | { type: "connected" } | { type: "gamesUpdated"; payload: {
	games: Game[],
} } | { type: "joining"; payload: {
	id: number,
} } | { type: "launching"; payload: {
	launch: GameLaunch,
} } | { type: "joinFailed"; payload: {
	id: number,
	reason: string,
} } | { type: "inGame" } | { type: "launchFailed"; payload: {
	reason: string,
} } | { type: "disconnected" };

export type LobbyState = {
	status: LobbyStatus,
	games: Game[],
	join: JoinState,
};

export type LobbyStatus = "disconnected" | "connecting" | "connected";

export type NavCommand = { type: "select"; payload: {
	tab: Tab,
} };

export type NavEvent = { type: "tabSelected"; payload: {
	tab: Tab,
} };

export type NavState = {
	activeTab: Tab,
};

/**  An authenticated FAF player. Grows later (country, avatar, ratings…). */
export type Player = {
	id: number,
	name: string,
};

/**  Things the UI can ask the session service to do. */
export type SessionCommand = 
/**  Handshake: ask the backend to report readiness. */
{ type: "hello" };

/**  Things that have happened to the session. The only way [`SessionState`] changes. */
export type SessionEvent = { type: "connecting" } | { type: "backendReady"; payload: {
	version: string,
} } | { type: "disconnected" };

/**  State of the session slice. */
export type SessionState = {
	/**  Version reported by the Rust backend once it is ready. */
	backendVersion: string,
	status: ConnectionStatus,
};

export type SettingsCommand = 
/**  Load persisted settings (dispatched once at startup). */
{ type: "load" } | 
/**  Change the active theme (persisted). */
{ type: "setTheme"; payload: {
	theme: Theme,
} };

export type SettingsEvent = 
/**  Settings were loaded from disk (startup) — replaces the whole slice. */
{ type: "loaded"; payload: {
	settings: SettingsState,
} } | 
/**  The theme changed. */
{ type: "themeChanged"; payload: {
	theme: Theme,
} };

/**  Persisted preferences. Serialized verbatim to the settings file. */
export type SettingsState = {
	theme: Theme,
};

/**
 *  A top-level destination. Most are placeholders today; each gets its feature
 *  slice as it lands. The frontend tab registry maps these 1:1 to views.
 */
export type Tab = "home" | "news" | "chat" | "play" | "replays" | "maps" | "mods" | "leaderboard" | "units" | "settings";

/**
 *  The active UI theme. Each variant maps to a `[data-theme]` token set in the
 *  frontend; adding a theme is a token block + a variant here (no UI changes).
 */
export type Theme = 
/**  ForgeMapToolkit dark — the signature warm near-black aesthetic. */
"forgeDark" | 
/**  ForgeMapToolkit light. */
"forgeLight" | 
/**  FAF Java client aesthetic. */
"javaClient" | 
/**  FAF Python client aesthetic. */
"pythonClient";
