// AUTO-GENERATED by `cargo run -p faf-ipc --bin export-bindings`.
// Source of truth: crates/faf-domain. DO NOT EDIT BY HAND.

// This file has been generated by Specta. Do not edit this file manually.
export type AppCommand = { kind: "Session"; command: SessionCommand } | { kind: "Auth"; command: AuthCommand } | { kind: "Nav"; command: NavCommand } | { kind: "Lobby"; command: LobbyCommand } | { kind: "Settings"; command: SettingsCommand };

export type AppEvent = { kind: "Session"; event: SessionEvent } | { kind: "Auth"; event: AuthEvent } | { kind: "Nav"; event: NavEvent } | { kind: "Lobby"; event: LobbyEvent } | { kind: "Settings"; event: SettingsEvent };

/**  The complete client state. One field per domain slice. */
export type AppState = {
	session: SessionState,
	auth: AuthState,
	nav: NavState,
	lobby: LobbyState,
	settings: SettingsState,
};

/**  What the UI can ask the auth service to do. */
export type AuthCommand = { type: "login" } | { type: "logout" };

/**  The only way [`AuthState`] changes. */
export type AuthEvent = { type: "loginStarted" } | { type: "loggedIn"; payload: {
	player: Player,
} } | { type: "loginFailed"; payload: {
	message: string,
} } | { type: "loggedOut" };

export type AuthState = {
	status: AuthStatus,
	player: Player | null,
	error: string | null,
};

export type AuthStatus = "loggedOut" | "loggingIn" | "loggedIn" | "failed";

/**  Connection state of the backend session. */
export type ConnectionStatus = "disconnected" | "connecting" | "connected";

/**  An open game in the lobby. */
export type Game = {
	id: number,
	title: string,
	host: string,
	players: number,
	maxPlayers: number,
	map: string,
};

export type LobbyCommand = { type: "connect" } | { type: "disconnect" };

export type LobbyEvent = { type: "connecting" } | { type: "connected" } | { type: "gamesUpdated"; payload: {
	games: Game[],
} } | { type: "disconnected" };

export type LobbyState = {
	status: LobbyStatus,
	games: Game[],
};

export type LobbyStatus = "disconnected" | "connecting" | "connected";

export type NavCommand = { type: "select"; payload: {
	tab: Tab,
} };

export type NavEvent = { type: "tabSelected"; payload: {
	tab: Tab,
} };

export type NavState = {
	activeTab: Tab,
};

/**  An authenticated FAF player. Grows later (country, avatar, ratings…). */
export type Player = {
	id: number,
	name: string,
};

/**  Things the UI can ask the session service to do. */
export type SessionCommand = 
/**  Handshake: ask the backend to report readiness. */
{ type: "hello" };

/**  Things that have happened to the session. The only way [`SessionState`] changes. */
export type SessionEvent = { type: "connecting" } | { type: "backendReady"; payload: {
	version: string,
} } | { type: "disconnected" };

/**  State of the session slice. */
export type SessionState = {
	/**  Version reported by the Rust backend once it is ready. */
	backendVersion: string,
	status: ConnectionStatus,
};

export type SettingsCommand = 
/**  Load persisted settings (dispatched once at startup). */
{ type: "load" } | 
/**  Change the active theme (persisted). */
{ type: "setTheme"; payload: {
	theme: Theme,
} };

export type SettingsEvent = 
/**  Settings were loaded from disk (startup) — replaces the whole slice. */
{ type: "loaded"; payload: {
	settings: SettingsState,
} } | 
/**  The theme changed. */
{ type: "themeChanged"; payload: {
	theme: Theme,
} };

/**  Persisted preferences. Serialized verbatim to the settings file. */
export type SettingsState = {
	theme: Theme,
};

/**
 *  A top-level destination. Most are placeholders today; each gets its feature
 *  slice as it lands. The frontend tab registry maps these 1:1 to views.
 */
export type Tab = "home" | "news" | "chat" | "play" | "replays" | "maps" | "mods" | "leaderboard" | "units" | "settings";

/**
 *  The active UI theme. Each variant maps to a `[data-theme]` token set in the
 *  frontend; adding a theme is a token block + a variant here (no UI changes).
 */
export type Theme = 
/**  ForgeMapToolkit dark — the signature warm near-black aesthetic. */
"forgeDark" | 
/**  ForgeMapToolkit light. */
"forgeLight" | 
/**  FAF Java client aesthetic. */
"javaClient" | 
/**  FAF Python client aesthetic. */
"pythonClient";
