// AUTO-GENERATED by `cargo run -p faf-ipc --bin export-bindings`.
// Source of truth: crates/faf-domain. DO NOT EDIT BY HAND.

// This file has been generated by Specta. Do not edit this file manually.
export type AppCommand = { kind: "Session"; command: SessionCommand } | { kind: "Auth"; command: AuthCommand } | { kind: "Nav"; command: NavCommand } | { kind: "Chat"; command: ChatCommand } | { kind: "Lobby"; command: LobbyCommand } | { kind: "Replays"; command: ReplayCommand } | { kind: "Maps"; command: MapsCommand } | { kind: "Mods"; command: ModsCommand } | { kind: "Leaderboard"; command: LeaderboardCommand } | { kind: "Settings"; command: SettingsCommand };

export type AppEvent = { kind: "Session"; event: SessionEvent } | { kind: "Auth"; event: AuthEvent } | { kind: "Nav"; event: NavEvent } | { kind: "Chat"; event: ChatEvent } | { kind: "Lobby"; event: LobbyEvent } | { kind: "Replays"; event: ReplayEvent } | { kind: "Maps"; event: MapsEvent } | { kind: "Mods"; event: ModsEvent } | { kind: "Leaderboard"; event: LeaderboardEvent } | { kind: "Settings"; event: SettingsEvent };

/**  The complete client state. One field per domain slice. */
export type AppState = {
	session: SessionState,
	auth: AuthState,
	nav: NavState,
	chat: ChatState,
	lobby: LobbyState,
	replays: ReplayState,
	maps: MapsState,
	mods: ModsState,
	leaderboard: LeaderboardState,
	settings: SettingsState,
};

/**  What the UI can ask the auth service to do. */
export type AuthCommand = { type: "login" } | { type: "logout" };

/**  The only way [`AuthState`] changes. */
export type AuthEvent = { type: "loginStarted" } | { type: "loggedIn"; payload: {
	player: Player,
} } | { type: "loginFailed"; payload: {
	message: string,
} } | { type: "loggedOut" };

export type AuthState = {
	status: AuthStatus,
	player: Player | null,
	error: string | null,
};

export type AuthStatus = "loggedOut" | "loggingIn" | "loggedIn" | "failed";

export type ChatCommand = 
/**
 *  Carries the username because IRC needs an explicit NICK/SASL authzid;
 *  the frontend already knows it (`auth.player.name`), so no new backend
 *  "current user" plumbing is needed — same posture as `LobbyCommand::Join`
 *  carrying UI-known data.
 */
{ type: "connect"; payload: {
	username: string,
} } | { type: "sendMessage"; payload: {
	content: string,
} } | { type: "disconnect" };

export type ChatEvent = { type: "connecting" } | { type: "connected" } | { type: "messageReceived"; payload: {
	message: ChatMessage,
} } | { type: "usersUpdated"; payload: {
	users: string[],
} } | { type: "disconnected" };

/**
 *  A single chat message. `id`/`timestamp` are `String`: `id` avoids the
 *  i64/specta boundary issue noted in `lobby.rs`'s `Game`, and `timestamp` is
 *  stamped by the port (real IRC has no such field; the client stamps
 *  receipt time) — keeping this pure slice free of a clock dependency.
 */
export type ChatMessage = {
	id: string,
	sender: string,
	content: string,
	timestamp: string,
};

export type ChatState = {
	status: ChatStatus,
	messages: ChatMessage[],
	/**  Usernames currently in the channel, sorted for stable rendering. */
	users: string[],
};

export type ChatStatus = "disconnected" | "connecting" | "connected";

/**  Connection state of the backend session. */
export type ConnectionStatus = "disconnected" | "connecting" | "connected";

/**  An open game in the lobby. */
export type Game = {
	id: number,
	title: string,
	host: string,
	players: number,
	maxPlayers: number,
	map: string,
	/**
	 *  The featured mod (e.g. `faf`). Needed to build a replay's `/init`
	 *  argument when watching this game live. Wire key on `game_info` is
	 *  `featured_mod`, unrelated to `GameLaunch`'s `mod`.
	 */
	modName: string,
	visibility: GameVisibility,
	passwordProtected: boolean,
	/**  e.g. `custom`, `coop`, `matchmaker` — the server's `game_type`. */
	gameType: string,
	/**
	 *  Display names of enabled sim mods (server sends `{uid: name}`; only the
	 *  names are needed to render the tile/detail panel).
	 */
	simMods: string[],
	ratingType: string,
	ratingMin: number | null,
	ratingMax: number | null,
	enforceRatingRange: boolean,
	/**
	 *  Team number (as sent by the server, e.g. `"1"`, `"2"`, `"-1"` for no
	 *  team/FFA) → player logins.
	 */
	teams: { [key in string]: string[] },
};

/**
 *  The server's `game_launch` order — everything the connectivity + launch chain
 *  (a later phase) needs to actually start the game. For now we only model and
 *  surface it; nothing acts on it yet. Mirrors the relevant fields of the Python
 *  client's `GameLaunchCommand` (`src/protocol/lobbyprotocol.py`).
 */
export type GameLaunch = {
	uid: number,
	/**  The featured mod (e.g. `faf`). Wire key is `mod`, a Rust keyword. */
	mod: string,
	name: string,
	mapname: string,
	gameType: string,
	ratingType: string,
	/**
	 *  Raw launch args from the server (the FA command line is built from these
	 *  plus client-side player info in the launch phase).
	 */
	args: string[],
};

/**
 *  Who can see/join a hosted game. Wire values on `game_info`/`game_host` are
 *  lowercase (`public`/`friends`).
 */
export type GameVisibility = "public" | "friends";

/**
 *  What the UI sends to host a new game. Mirrors the fields the server's
 *  `game_host` command reads (`lobbyconnection.py::command_game_host`).
 */
export type HostGameRequest = {
	title: string,
	mapname: string,
	/**  The featured mod / gamemode (e.g. `faf`, `fafbeta`, `fafdevelop`, `nomads`). */
	featuredMod: string,
	password: string | null,
	visibility: GameVisibility,
	ratingMin: number | null,
	ratingMax: number | null,
	enforceRatingRange: boolean,
	/**  UIDs of the sim/UI mods to enable. */
	simMods: string[],
};

/**
 *  Where a host attempt stands. Distinct from [`JoinState`]: hosting and
 *  joining are different flows (the Host dialog needs its own success/failure
 *  signal to know when to close), even though both end with the game launching.
 */
export type HostState = { type: "idle" } | { type: "hosting" } | { type: "hosted"; payload: {
	id: number,
} } | { type: "failed"; payload: {
	reason: string,
} };

/**
 *  A map folder already present in the user's maps folder (mirrors the
 *  Python client's `MapsManagerDialog`/`fa.maps.getUserMaps`). Just the
 *  folder name and a display name derived from it — the Python client's
 *  `getDisplayName` fallback for non-official maps, not a full scenario.lua
 *  parse (that's `InstalledMapsCache`, a later-phase nicety).
 */
export type InstalledMap = {
	folderName: string,
	displayName: string,
};

/**
 *  A mod folder already present in the user's mods folder, cross-referenced
 *  against `game.prefs`'s `active_mods` table for `enabled`. Mirrors the
 *  Python client's `ModInfo` (`vaults/modvault/utils.py`) as parsed from
 *  each folder's `mod_info.lua`.
 */
export type InstalledMod = {
	folderName: string,
	uid: string,
	displayName: string,
	version: string,
	author: string,
	modType: ModType,
	enabled: boolean,
};

/**
 *  Where a join attempt stands. Distinct from [`LobbyStatus`] (the connection):
 *  you can be `Connected` and `Idle`, or `Connected` and `Joining`.
 */
export type JoinState = { type: "idle" } | { type: "joining"; payload: {
	id: number,
} } | 
/**
 *  The server sent `game_launch`; the launch order is modeled. If real launch
 *  is enabled, the connectivity chain (ICE adapter + relay + game process)
 *  starts next, moving to [`Self::InGame`].
 */
{ type: "launched"; payload: {
	launch: GameLaunch,
} } | 
/**  The ICE adapter and game process were started; relay traffic is flowing. */
{ type: "inGame" } | 
/**  The server rejected the join (game not ready, host left, bad password). */
{ type: "failed"; payload: {
	id: number,
	reason: string,
} } | 
/**  The local launch chain failed (adapter/relay/game couldn't start). */
{ type: "launchFailed"; payload: {
	reason: string,
} };

export type LeaderboardCommand = { type: "loadLeagues" } | { type: "selectLeague"; payload: {
	leagueId: number,
} } | { type: "loadGlobal" };

/**
 *  One row in a rankings table — either a ladder bracket's active-season
 *  entry or a global-rating entry (see the module docs for which fields
 *  apply to which).
 */
export type LeaderboardEntry = {
	/**  Computed client-side from sort order — not an API field. */
	rank: number,
	playerName: string,
	/**
	 *  League placement score. `None` for global-rating entries, which
	 *  have no league/season concept.
	 */
	score: number | null,
	/**
	 *  The player's underlying TrueSkill-derived rating for this game
	 *  mode — present for both ladder and global entries.
	 */
	rating: number | null,
	gamesPlayed: number,
	/**
	 *  e.g. `"Bronze III"`. `None` for global-rating entries (no
	 *  divisions there), or if a ladder player has none yet (still in
	 *  placement games).
	 */
	division: string | null,
	/**
	 *  `divisionIndex * 1000 + subdivisionIndex` — higher is a higher-tier
	 *  division. A separate sortable field from `division` (the display
	 *  string) so the frontend can put the highest division first without
	 *  parsing/guessing an order out of `nameKey` text.
	 */
	divisionOrder: number | null,
};

export type LeaderboardEvent = { type: "leaguesLoading" } | { type: "leaguesLoaded"; payload: {
	leagues: League[],
} } | { type: "leaguesLoadFailed"; payload: {
	reason: string,
} } | { type: "entriesLoading"; payload: {
	leagueId: number,
} } | { type: "entriesLoaded"; payload: {
	leagueId: number,
	entries: LeaderboardEntry[],
} } | { type: "entriesLoadFailed"; payload: {
	reason: string,
} } | { type: "globalLoading" } | { type: "globalLoaded"; payload: {
	entries: LeaderboardEntry[],
} } | { type: "globalLoadFailed"; payload: {
	reason: string,
} };

export type LeaderboardState = {
	leagues: League[],
	leaguesStatus: LeaderboardStatus,
	selectedLeagueId: number | null,
	entries: LeaderboardEntry[],
	entriesStatus: LeaderboardStatus,
	globalEntries: LeaderboardEntry[],
	globalStatus: LeaderboardStatus,
};

/**
 *  Status of a leagues/entries/global fetch (mirrors
 *  [`crate::state::MapListStatus`] — kept local since these load
 *  independently).
 */
export type LeaderboardStatus = { type: "idle" } | { type: "loading" } | { type: "ready" } | { type: "failed"; payload: {
	reason: string,
} };

/**  One ladder bracket, as listed from the FAF Data API (`GET /data/league`). */
export type League = {
	id: number,
	/**
	 *  e.g. `"ladder1v1"` — shown as-is; this client has no i18n table to
	 *  resolve a display name from (same pragmatic choice already made for
	 *  mod technical names in the replay vault).
	 */
	technicalName: string,
};

/**
 *  Enough to identify and launch a live (in-progress) game's replay stream.
 *  Comes from a [`crate::state::Game`] the lobby already surfaced as playing.
 */
export type LiveReplayTarget = {
	uid: number,
	/**
	 *  Wire key on the launch args is `mod`, a Rust keyword; the struct field
	 *  avoids it like `GameLaunch::mod_name` does.
	 */
	modName: string,
	map: string,
};

export type LobbyCommand = { type: "connect" } | { type: "join"; payload: {
	id: number,
} } | { type: "disconnect" } | { type: "host"; payload: {
	req: HostGameRequest,
} };

export type LobbyEvent = { type: "connecting" } | { type: "connected" } | { type: "gamesUpdated"; payload: {
	games: Game[],
} } | { type: "liveGamesUpdated"; payload: {
	games: Game[],
} } | { type: "joining"; payload: {
	id: number,
} } | { type: "launching"; payload: {
	launch: GameLaunch,
} } | { type: "joinFailed"; payload: {
	id: number,
	reason: string,
} } | { type: "inGame" } | { type: "launchFailed"; payload: {
	reason: string,
} } | { type: "disconnected" } | { type: "hosting" } | { type: "hosted"; payload: {
	id: number,
} } | { type: "hostFailed"; payload: {
	reason: string,
} } | { type: "playerRatingsUpdated"; payload: {
	ratings: PlayerRating[],
} };

export type LobbyState = {
	status: LobbyStatus,
	games: Game[],
	/**
	 *  Games currently in progress — not joinable, but watchable via a live
	 *  replay (see `faf-app`'s `ReplayPort::watch_live`).
	 */
	liveGames: Game[],
	join: JoinState,
	host: HostState,
	/**  Rating cache (login → rating), fed by the server's `player_info` stream. */
	ratings: { [key in string]: number },
};

export type LobbyStatus = "disconnected" | "connecting" | "connected";

/**
 *  One `.fafreplay` file already on disk, from the shared FAF replay folder
 *  (`%ProgramData%\FAForever\replays` on Windows — every FAF client writes
 *  here, mirrors `DataPrefs.getReplaysDirectory()` in the Java client). Read
 *  from just the file's JSON header line, not the full compressed body.
 */
export type LocalReplay = {
	path: string,
	uid: number | null,
	map: string,
	modName: string,
	title: string,
};

/**  Status of an install/uninstall action for one map folder. */
export type MapInstallStatus = { type: "idle" } | { type: "installing"; payload: {
	folderName: string,
} } | { type: "failed"; payload: {
	reason: string,
} };

/**
 *  Status of a list fetch (vault or installed) — separate from
 *  [`InstallStatus`], since browsing and installing are independent
 *  (mirrors [`crate::state::VaultStatus`] for replays, kept local to avoid
 *  coupling the two slices).
 */
export type MapListStatus = { type: "idle" } | { type: "loading" } | { type: "ready" } | { type: "failed"; payload: {
	reason: string,
} };

export type MapsCommand = 
/**  Fetch the map vault (mirrors `MapVault`'s default "All" browse query). */
{ type: "loadVault" } | 
/**  Scan the user's maps folder (mirrors `MapsManagerDialog::setup_maplist`). */
{ type: "loadInstalled" } | 
/**  Download and extract a map version's zip (mirrors `maps._doDownloadMap`). */
{ type: "installMap"; payload: {
	folderName: string,
	downloadUrl: string,
} } | 
/**  Delete a map folder (mirrors `MapsManagerDialog::delete_map`). */
{ type: "uninstallMap"; payload: {
	folderName: string,
} };

export type MapsEvent = { type: "vaultLoading" } | { type: "vaultLoaded"; payload: {
	maps: VaultMap[],
} } | { type: "vaultLoadFailed"; payload: {
	reason: string,
} } | { type: "installedLoading" } | { type: "installedLoaded"; payload: {
	maps: InstalledMap[],
} } | { type: "installedLoadFailed"; payload: {
	reason: string,
} } | { type: "installing"; payload: {
	folderName: string,
} } | 
/**
 *  Install succeeded — carries the freshly-scanned installed list so the
 *  UI doesn't need a separate `LoadInstalled` round-trip (mirrors the
 *  Python client's `MapsManagerDialog` re-scanning after every change).
 */
{ type: "installed"; payload: {
	installed: InstalledMap[],
} } | { type: "installFailed"; payload: {
	reason: string,
} } | { type: "uninstalled"; payload: {
	installed: InstalledMap[],
} } | { type: "uninstallFailed"; payload: {
	reason: string,
} };

export type MapsState = {
	vault: VaultMap[],
	vaultStatus: MapListStatus,
	installed: InstalledMap[],
	installedStatus: MapListStatus,
	installStatus: MapInstallStatus,
};

/**
 *  Status of an install/uninstall action for one mod. Mirrors
 *  [`crate::state::MapInstallStatus`].
 */
export type ModInstallStatus = { type: "idle" } | { type: "installing"; payload: {
	uid: string,
} } | { type: "failed"; payload: {
	reason: string,
} };

/**
 *  Status of a list fetch (vault or installed) — separate from
 *  [`ModInstallStatus`]/[`ModToggleStatus`], mirrors
 *  [`crate::state::MapListStatus`].
 */
export type ModListStatus = { type: "idle" } | { type: "loading" } | { type: "ready" } | { type: "failed"; payload: {
	reason: string,
} };

/**
 *  Status of an enable/disable action for one installed mod. Separate from
 *  [`ModInstallStatus`] since toggling and installing are independent
 *  actions a user could trigger back to back.
 */
export type ModToggleStatus = { type: "idle" } | { type: "toggling"; payload: {
	uid: string,
} } | { type: "failed"; payload: {
	reason: string,
} };

/**
 *  UI mods are cosmetic/interface-only and freely toggleable; SIM mods
 *  affect game logic and matter for replay/multiplayer compatibility.
 *  Mirrors the Python client's `ui_only` flag (`ModInfo.ui_only`) and the
 *  Java client's `ModType` enum.
 */
export type ModType = "ui" | "sim";

export type ModsCommand = 
/**
 *  Fetch the mod vault (newest first — mirrors the current default
 *  posture of `MapsCommand::LoadVault`).
 */
{ type: "loadVault" } | 
/**  Scan the user's mods folder (mirrors `MapsCommand::LoadInstalled`). */
{ type: "loadInstalled" } | 
/**
 *  Download and extract a mod version's zip (mirrors
 *  `MapsCommand::InstallMap`).
 */
{ type: "installMod"; payload: {
	uid: string,
	downloadUrl: string,
} } | 
/**  Delete a mod folder (mirrors `MapsCommand::UninstallMap`). */
{ type: "uninstallMod"; payload: {
	folderName: string,
} } | 
/**
 *  Enable or disable an installed mod without uninstalling it (writes
 *  `game.prefs`'s `active_mods` table).
 */
{ type: "toggleMod"; payload: {
	uid: string,
	enabled: boolean,
} };

export type ModsEvent = { type: "vaultLoading" } | { type: "vaultLoaded"; payload: {
	mods: VaultMod[],
} } | { type: "vaultLoadFailed"; payload: {
	reason: string,
} } | { type: "installedLoading" } | { type: "installedLoaded"; payload: {
	mods: InstalledMod[],
} } | { type: "installedLoadFailed"; payload: {
	reason: string,
} } | { type: "installing"; payload: {
	uid: string,
} } | 
/**
 *  Install succeeded — carries the freshly-scanned installed list so
 *  the UI doesn't need a separate `LoadInstalled` round-trip (mirrors
 *  `MapsEvent::Installed`).
 */
{ type: "installed"; payload: {
	installed: InstalledMod[],
} } | { type: "installFailed"; payload: {
	reason: string,
} } | { type: "uninstalled"; payload: {
	installed: InstalledMod[],
} } | { type: "uninstallFailed"; payload: {
	reason: string,
} } | { type: "toggling"; payload: {
	uid: string,
} } | { type: "toggled"; payload: {
	installed: InstalledMod[],
} } | { type: "toggleFailed"; payload: {
	reason: string,
} };

export type ModsState = {
	vault: VaultMod[],
	vaultStatus: ModListStatus,
	installed: InstalledMod[],
	installedStatus: ModListStatus,
	installStatus: ModInstallStatus,
	toggleStatus: ModToggleStatus,
};

export type NavCommand = { type: "select"; payload: {
	tab: Tab,
} };

export type NavEvent = { type: "tabSelected"; payload: {
	tab: Tab,
} };

export type NavState = {
	activeTab: Tab,
};

/**  An authenticated FAF player. Grows later (country, avatar, ratings…). */
export type Player = {
	id: number,
	name: string,
};

/**
 *  A player's rating, as last reported by the server's `player_info` stream.
 *  Kept as a flat cache (login → rating) rather than a full social/friends
 *  slice — just enough to derive a game's average rating from its `teams`.
 */
export type PlayerRating = {
	login: string,
	rating: number,
};

export type ReplayCommand = { type: "watchLive"; payload: LiveReplayTarget } | 
/**
 *  Play a `.fafreplay`/`.scfareplay` file by path — used both for the
 *  file-picker flow and for watching a [`LocalReplay`] row.
 */
{ type: "openFile"; payload: {
	path: string,
} } | 
/**  Fetch the global "newest replays" feed from the vault. */
{ type: "loadVault" } | 
/**  Download and play a vault replay by its game id. */
{ type: "watchVault"; payload: {
	uid: number,
} } | 
/**  Scan the shared FAF replay folder for local `.fafreplay` files. */
{ type: "loadLocal" };

export type ReplayEvent = { type: "connecting" } | 
/**
 *  `warning` carries a non-fatal prep-step issue (see
 *  [`ReplayState::last_warning`]) — `None` when prep was clean/skipped.
 */
{ type: "playing"; payload: {
	uid: number | null,
	warning: string | null,
} } | { type: "failed"; payload: {
	reason: string,
} } | 
/**
 *  The replay session ended (game process exited / stream closed) — back
 *  to idle so the UI can start another one.
 */
{ type: "closed" } | { type: "vaultLoading" } | { type: "vaultLoaded"; payload: {
	replays: VaultReplay[],
} } | { type: "vaultLoadFailed"; payload: {
	reason: string,
} } | { type: "localLoading" } | { type: "localLoaded"; payload: {
	replays: LocalReplay[],
} } | { type: "localLoadFailed"; payload: {
	reason: string,
} };

export type ReplayPlayer = {
	name: string,
	/**
	 *  1=UEF, 2=Aeon, 3=Cybran, 4=Seraphim — matches the FAF API's
	 *  `playerStats.faction` convention.
	 */
	faction: number | null,
	/**
	 *  `round(mean - 3*deviation)` at game time, the same "displayed rating"
	 *  formula the Python and Java clients use.
	 */
	rating: number | null,
};

export type ReplayState = {
	status: ReplayStatus,
	/**
	 *  A non-fatal issue from the last launch's prep steps (engine
	 *  version/map staging — see `infra/game_updater.rs`), e.g. "could not
	 *  stage map X". `None` means the last launch's prep was clean or none
	 *  has happened yet. Separate from [`ReplayStatus::Failed`], which is
	 *  for launches that didn't happen at all — this is for ones that did,
	 *  but might misbehave in FA itself (stuck loading screen, etc.) because
	 *  a non-fatal prep step failed. Cleared on the next [`ReplayEvent::Connecting`].
	 */
	lastWarning: string | null,
	vault: VaultReplay[],
	vaultStatus: VaultStatus,
	local: LocalReplay[],
	localStatus: VaultStatus,
};

export type ReplayStatus = { type: "idle" } | { type: "connecting" } | 
/**
 *  FA has been launched. `uid` is `None` for a local file whose header
 *  failed to parse (playback still proceeds; we just can't label it).
 */
{ type: "playing"; payload: {
	uid: number | null,
} } | { type: "failed"; payload: {
	reason: string,
} };

export type ReplayTeam = {
	team: number,
	players: ReplayPlayer[],
};

/**  Things the UI can ask the session service to do. */
export type SessionCommand = 
/**  Handshake: ask the backend to report readiness. */
{ type: "hello" };

/**  Things that have happened to the session. The only way [`SessionState`] changes. */
export type SessionEvent = { type: "connecting" } | { type: "backendReady"; payload: {
	version: string,
} } | { type: "disconnected" };

/**  State of the session slice. */
export type SessionState = {
	/**  Version reported by the Rust backend once it is ready. */
	backendVersion: string,
	status: ConnectionStatus,
};

export type SettingsCommand = 
/**  Load persisted settings (dispatched once at startup). */
{ type: "load" } | 
/**  Change the active theme (persisted). */
{ type: "setTheme"; payload: {
	theme: Theme,
} } | 
/**  Change the live-game FA install path (persisted). */
{ type: "setGamePath"; payload: {
	path: string,
} } | 
/**  Change the replay FA install path (persisted). */
{ type: "setReplayGamePath"; payload: {
	path: string,
} };

export type SettingsEvent = 
/**  Settings were loaded from disk (startup) — replaces the whole slice. */
{ type: "loaded"; payload: {
	settings: SettingsState,
} } | 
/**  The theme changed. */
{ type: "themeChanged"; payload: {
	theme: Theme,
} } | 
/**  The live-game FA install path changed. */
{ type: "gamePathChanged"; payload: {
	path: string,
} } | 
/**  The replay FA install path changed. */
{ type: "replayGamePathChanged"; payload: {
	path: string,
} };

/**
 *  Persisted preferences. Serialized verbatim to the settings file.
 * 
 *  `game_path`/`replay_game_path` back the two FA installs
 *  [`crate::state::LobbyState`]/replay launch need (see
 *  `faf_app::infra::game::GameConfig`'s doc comment for why they're
 *  separate). Previously these were configurable only via the
 *  `FAF_GAME_PATH`/`FAF_REPLAY_GAME_PATH` env vars, which meant the app was
 *  effectively unusable for anyone who wasn't a developer exporting them by
 *  hand — empty string means "unset", same convention `GameConfig::faf()`
 *  already used for the env var. Read once at startup and baked into the
 *  launch config (see `src-tauri/src/lib.rs`), so a change here needs an app
 *  restart to take effect — no different from every other launch config
 *  (`api_base`, `content_base`, …) already being startup-only.
 */
export type SettingsState = {
	theme: Theme,
	gamePath: string,
	replayGamePath: string,
};

/**
 *  A top-level destination. Most are placeholders today; each gets its feature
 *  slice as it lands. The frontend tab registry maps these 1:1 to views.
 */
export type Tab = "home" | "news" | "chat" | "play" | "replays" | "maps" | "mods" | "leaderboard" | "units" | "settings";

/**
 *  The active UI theme. Each variant maps to a `[data-theme]` token set in the
 *  frontend; adding a theme is a token block + a variant here (no UI changes).
 */
export type Theme = 
/**  ForgeMapToolkit dark — the signature warm near-black aesthetic. */
"forgeDark" | 
/**  ForgeMapToolkit light. */
"forgeLight" | 
/**  FAF Java client aesthetic. */
"javaClient" | 
/**  FAF Python client aesthetic. */
"pythonClient";

/**
 *  One map version, as listed from the FAF Data API (`GET /data/map`,
 *  `include=latestVersion,author`). Mirrors the Python client's `Map` +
 *  `MapVersion` models (`src/api/models/Map.py`, `MapVersion.py`) — the
 *  client always looks at `map.latestVersion`, never older versions.
 */
export type VaultMap = {
	displayName: string,
	/**
	 *  `None` for maps without an uploader on record (mirrors `Map.author`
	 *  being optional in the Python model).
	 */
	author: string | null,
	/**
	 *  The directory name this version installs as, e.g. `scmp_009.v0001` —
	 *  the install/uninstall/"is this installed" key everywhere (mirrors
	 *  `MapVersion.folder_name`).
	 */
	folderName: string,
	maxPlayers: number,
	width: number,
	height: number,
	gamesPlayed: number,
	ranked: boolean,
	downloadUrl: string,
	thumbnailUrl: string,
};

/**
 *  One mod version, as listed from the FAF Data API (`GET /data/mod`,
 *  `include=latestVersion`) — the client always looks at `mod.latestVersion`,
 *  same posture as [`crate::state::VaultMap`].
 */
export type VaultMod = {
	displayName: string,
	/**
	 *  Flat attribute on the `mod` resource itself, not a relationship
	 *  (unlike [`crate::state::VaultMap`]'s `author`, which is a `player`
	 *  relationship) — confirmed against the Java client's `Mod.author`.
	 */
	author: string,
	/**
	 *  `latestVersion.uid` — the stable id matched against locally
	 *  installed mods and `game.prefs`'s `active_mods` table. Distinct
	 *  from the numeric JSON:API resource `id`.
	 */
	uid: string,
	/**
	 *  Stored as text — FAF mod versions aren't reliably semver (often a
	 *  bare integer).
	 */
	version: string,
	modType: ModType,
	ranked: boolean,
	downloadUrl: string,
	thumbnailUrl: string,
};

/**
 *  One entry in the global "newest replays" feed, as listed from the FAF
 *  Data API (`GET /data/game`, no player filter — mirrors the Java client's
 *  `OnlineReplayVaultController`'s `NEWEST` category). Just enough to render
 *  a row and trigger a download+play — not the full search/filter model the
 *  reference clients' vault tabs have (map/player/rating filters, "own
 *  replays only" toggle, are a later phase).
 */
export type VaultReplay = {
	uid: number,
	/**
	 *  `game.attributes.name` — the host-chosen lobby title (e.g. "all
	 *  welcome", "1200+"), distinct from the map name.
	 */
	title: string,
	map: string,
	/**
	 *  `mapVersion.thumbnailUrlSmall` straight from the API. Empty string if
	 *  missing (e.g. a generated/hidden map) — the frontend treats that as
	 *  "no thumbnail" rather than us modeling it as `Option`.
	 */
	mapThumbnailUrl: string,
	modName: string,
	/**  ISO 8601, straight from the API — rendering/formatting is a UI concern. */
	startTime: string,
	/**
	 *  Whether the file has actually finished uploading to content storage.
	 *  A "newest replays" listing includes very recent/still-processing
	 *  games too; both reference clients disable the Watch button until this
	 *  is `true` rather than filtering the row out entirely.
	 */
	replayAvailable: boolean,
	/**
	 *  `endTime - startTime` in seconds. `None` if either timestamp is
	 *  missing/unparseable (e.g. a game still in progress has no `endTime`).
	 */
	durationSeconds: number | null,
	teams: ReplayTeam[],
	/**
	 *  Average of all resolvable player ratings on the card — `None` if no
	 *  player's rating could be resolved.
	 */
	averageRating: number | null,
	reviewsAverage: number | null,
	reviewsCount: number | null,
};

/**
 *  Where the vault list stands. Separate from [`ReplayStatus`] (playback) —
 *  you can be browsing the vault (`Ready`) while also `Playing` a replay.
 */
export type VaultStatus = { type: "idle" } | { type: "loading" } | { type: "ready" } | { type: "failed"; payload: {
	reason: string,
} };
