//! IPC contract: the anti-drift boundary.
//!
//! Generates the TypeScript definitions for every type that crosses the Tauri
//! boundary ([`AppState`], [`AppCommand`], [`AppEvent`] and everything they
//! reference) straight from the Rust source of truth. The frontend imports the
//! result; no cross-boundary type is ever hand-written (ARCHITECTURE.md §3.7).
//!
//! Run `cargo run -p faf-ipc --bin export-bindings` to (re)generate
//! `ui/src/ipc/bindings.ts`. A CI check should fail if the output is stale.

use faf_domain::state::{ContributionProblem, ReviewProblem};
use faf_domain::{AppCommand, AppEvent, AppState};
use specta::Types;
use specta_typescript::Typescript;

pub const HEADER: &str = "\
// AUTO-GENERATED by `cargo run -p faf-ipc --bin export-bindings`.
// Source of truth: crates/faf-domain. DO NOT EDIT BY HAND.
";

/// Render the TypeScript bindings for the whole IPC surface.
///
/// Registering the three root types pulls in every referenced slice type
/// (SessionState, SessionEvent, …) transitively.
///
/// A handful of types have to be named explicitly because they are reachable
/// from neither: they are the *return* types of pure domain rules the frontend
/// owns a twin of, pinned by the conformance fixture (see
/// `ui/src/shared/trainingRules.ts`). Registering them here is what keeps those
/// twins from having to hand-write the union, which is the one thing this crate
/// exists to prevent.
pub fn typescript_bindings() -> Result<String, specta_typescript::Error> {
    let types = Types::default()
        .register::<AppState>()
        .register::<AppCommand>()
        .register::<AppEvent>()
        .register::<ReviewProblem>()
        .register::<ContributionProblem>();

    let body = Typescript::default().export(&types, specta_serde::Format)?;
    // Specta currently emits a space after several multiline union separators.
    // Keep the checked-in contract deterministic and `git diff --check` clean.
    let body = body
        .lines()
        .map(str::trim_end)
        .collect::<Vec<_>>()
        .join("\n");
    Ok(format!("{HEADER}\n{body}\n"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bindings_contain_root_types() {
        let ts = typescript_bindings().expect("export should succeed");
        for ty in ["AppState", "AppCommand", "AppEvent", "SessionState"] {
            assert!(ts.contains(ty), "bindings missing `{ty}`:\n{ts}");
        }
    }

    #[test]
    fn bindings_have_no_trailing_whitespace() {
        let ts = typescript_bindings().expect("export should succeed");
        assert!(ts.lines().all(|line| line.trim_end() == line));
    }
}
